### PR TITLE
Create separate core and rest modules

### PR DESCRIPTION
**Pull request by jekh**
This PR creates separate browsermob-core and browsermob-rest modules, as discussed in PR #144. Since most files in the repo were moved into subdirectories, the changeset is huge. Here's a summary of the "meaty" changes for review:
- Version has changed to 2.1.0-SNAPSHOT. There is now a separate 2.0 branch with the legacy architecture.
- New browsermob-dist module: this is the module that actually builds the zip file (this is the recommended approach with multi-module builds).
- Maven shade plugin: browsermob-dist uses shade to create a runnable fat jar, rather than using the appassembler plugin. The maven assembly plugin still creates the zip file, but the zip now only contains a few files (readme, javadoc and sources jars, scripts to run the app, and the single fat jar). This will give us more control over the creation of the jar.
- browsermob-dist does not install the runnable jar into the maven repo; only the browsermob-core and browsermob-rest jars are installed.

As before, the "release" profile will create the zip file distributable (and now, the runnable fat jar).

The most interesting changes that could use some review are in the poms in each module, as well as the parent pom. @nite23 - could you take a look and let me know if you think this is a fair place to start with 2.1? If you spot any major deficiencies, I'll make the changes before merging. Otherwise, I'll merge and we can address any issues with additional PRs.

I'd like to get this major structural change merged fairly soon. Since we now have the stable 2.0 branch, master is going to be our development branch and won't be as stable as it was before the 2.0 release.

### CODE REVIEW

**Comment by nite23** [comment]
Great job! I like the big single jar solution. I think this can be merged, the only thing I'd improve are redundant dependencies... I moved them around a bit, and it seems that only dep that's currently shared between the modules is jUnit:
https://github.com/nite23/browsermob-proxy/commit/f4c3320f586dbbf946aa156a4db15f9b8b140db6

**Comment by jekh** [comment]
Thanks! There were some merge conflicts between the cleaned-up dependencies and some of my later commits, so I manually merged them in this commit: 98aadbb. Can you take a second look to make sure everything looks good?

One question -- I didn't see guice-multibindings in your changeset, but I wasn't sure if that was on purpose or not. I left it in, but I'll take it out if you meant to remove it. I honestly don't know if we have a runtime dependency on it or not. dependency:analyze says it's unused, but I'm not sure if it's used indirectly.

FYI -- in the two later commits I updated the slf4j version to the latest and replaced the transitive dependency on commons-logging from httpclient with slf4j.

**Comment by jekh** [comment]
@nite23 -- just added you as a collaborator on my repo so feel free to push any changes directly to the PR branch.

**Comment by nite23** [comment]
guice-multibindings and guice-servlet are pulled in by sitebricks, so it's not needed to declare them explicitly. But since we'll remove sitebricks soon, it's fine to leave them in the pom.

I added a slf4j binding so that we have some logging output when we run the tests.

**Pull request merged**
