### PR TITLE
Fixed bug in which URI path and query string were wrongly decoded

### PR DESCRIPTION
**Pull request by AndreaCatalucci**

### CODE REVIEW

**Comment by jekh** [comment]
Thanks for the PR. How are the path and query string being wrong decoded currently? Do you have an example, preferably a self-contained test case?

Also the travis-ci build failed for Java 7, you'll want to address that issue as BMP does target Java 7 and 8.

**Comment by AndreaCatalucci** [comment]
Sorry, the build failed due to some unused imports. Fixed now.
We included some unit tests that reproduce the problem: actually one of the preexisting tests did fail due to this bug, but we added other two to be more specific.

**Comment by jekh** [comment]
@AndreaCatalucci - I implemented your fix in PR #388, but with some code style and documentation changes. It's merged to master now, so if that looks good to you I'll close this PR.

**Comment by fsvehla** [comment]
@jekh When is the next release planned?

**Comment by AndreaCatalucci** [comment]
Yes, that looks good: thank you! Hope to see a release with this fix soon.

**Comment by fsvehla** [comment]
@jekh Maybe we can get a snapshot build? :)

**Comment by jekh** [comment]
@fsvehla - I'm working on one more feature that I want to get in before the next release. Time permitting, by this weekend, otherwise ~2 weeks.

**Pull request closed without merging**
